### ISSUE TITLE
might add info how to make emmet work too

### ISSUE THREAD

**Issue by CMQNordic** [vunguyentuan/vscode-postcss#1]
Great extension. Hard to fins both syntax highlighting AND autocompletion/intellisense to work out of the box! Works great.

Maybe you could mention in extension info that it is easy to add emmet support too!

 I add in my settings.json follwing and then for example writnig "pos:s" extends to "position: static;" by emmet as expected
 "emmet.includeLanguages": {
    "postcss": "css"
  },
  "emmet.syntaxProfiles": {
    "postcss": "css"
  },

Support color preview would be great!

**Comment by vunguyentuan** [comment]
Thanks, I've added
