### ISSUE TITLE
Highlighting for nesting not working

### ISSUE THREAD

**Issue by dwd0tcom** [vunguyentuan/vscode-postcss#2]
Hey! Glad I found your plug-in. Seems to be the only one which is maintained. Thanks! Could you somehow implement the feature to highlight nested classes?

![image](https://user-images.githubusercontent.com/9768158/150354997-9f51df06-5027-4a46-8e21-e1af0ddeae93.png)

**Comment by vunguyentuan** [comment]
This should be solved!

**Comment by patrulea** [comment]
Nesting with `@nest` at-rules doesn’t seem to be supported yet.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/33817380/236956091-ebc2b26b-d7b4-4baa-aa12-1b84bd69da05.png">
