### ISSUE TITLE
Lack of text highlighting and semicolon error

### ISSUE THREAD

**Issue by stolar-code** [vunguyentuan/vscode-postcss#3]
Hi, first of all I would like to thank you for doing a good job with this plugin and for IntelliSense compatibility. Compared to other `PostCss` supporting plugins, yours is the best.

However, I am struggling with some bugs....
The first is the lack of text highlighting while using `@define-mixin` and the second is the error `{ expectedpostcss(css-lcurlyexpected)` at `@mixin` line, ofcourse after adding brackets error disappear

![image](https://user-images.githubusercontent.com/65081438/150690564-adf3cee2-da55-4bdb-8b70-64486e068676.png)
![image](https://user-images.githubusercontent.com/65081438/150690579-66f660ad-2243-4720-9550-76c8e782a094.png)
![image](https://user-images.githubusercontent.com/65081438/150690768-7427968e-fbf5-40ed-865d-c2ba91851477.png)

Hopefully fixing it won't be a big challenge for you!

Thank you in advance 🙏

**Comment by spacedawwwg** [comment]
Just came to report the same issues.

**Comment by vunguyentuan** [comment]
This should be solved!

**Comment by vunguyentuan** [comment]
@spacedawwwg @stolar-code Let me know if you guys have this issue again and if you like this plugin please leave a comment on this https://marketplace.visualstudio.com/items?itemName=vunguyentuan.vscode-postcss. 

It means a lot to me!

**Comment by stolar-code** [comment]
@vunguyentuan To be completely honest with you it's even worse than it was ;D

![postcss](https://user-images.githubusercontent.com/65081438/159119585-f3e56922-9b3f-409e-961b-7532b9c77d1b.png)

ignoring the define mixin variable bug, now even "normal" styles have no text highlighting

**Comment by vunguyentuan** [comment]
@stolar-code I've released new version to fix text highlighting and @define-mixin syntax error, please help me verify if it :D

**Comment by stolar-code** [comment]
@vunguyentuan Ok, all the errors with `@define-mixin` are gone, and the text highlighting works properly now, good job!

After testing I found a couple of small bugs with highlighting tags and styles (one of them still applies to `mixins` ;D), but for that I will open a new issue

Again, well done!
