### ISSUE TITLE
@layer at-rule not recognised

### ISSUE THREAD

**Issue by nilaallj** [vunguyentuan/vscode-postcss#8]
The new [`@layer` at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) is not recognised in the editor, and it seems to block hover information and color decorators from showing.

This is as of recently supported natively in CSS in most browsers, so it should definitely be supported in a postcss extension.

<img width="270" alt="Screenshot of the issue" src="https://user-images.githubusercontent.com/9767434/167254217-34f9e8c1-045e-41e7-a6e8-945403eb7315.png">

Apart from this, I'd like to thank you for this superb extension and for keeping it maintained! ☀️

**Comment by vunguyentuan** [comment]
this should be fixed on latest version
